### ISSUE TITLE
Movimientos y físicas

### ISSUE THREAD

**Issue by Mimitrz** [CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood#10]
- [x] Controles
- [x] Interacción de elementos

**Comment by ManutiElArtista** [comment]
Subo los controles para jugar con teclado y con ratón. Faltaría el de mando.
Cuando esté el de mando, le ponemos el tick de completado.

![Controles](https://user-images.githubusercontent.com/90465393/140651178-2aaee4d6-bf0f-4274-b4c8-09294ed7785e.jpg)

**Comment by Rmp2901** [comment]
![Controles_Mando](https://user-images.githubusercontent.com/90465217/140656613-e630bcc6-11f1-4b43-b28a-b0568e6a5cff.jpg)

**Comment by Rmp2901** [comment]
![Controles_Mando](https://user-images.githubusercontent.com/90465217/140656737-bf2f2cfc-2b04-4996-b20c-9cc93d55c483.jpg)

**Comment by Rmp2901** [comment]
Actualizar L3: para Correr y Boton select para acceder al mapa directamente
Cruceta muestra HUD oculto durante 5 segundos.

**Comment by Rmp2901** [comment]
Pulsar y mantener Tab aparece interfaz oculta. 1, 2, 3 y 4 selección de arma.

**Comment by Rmp2901** [comment]
[Interaccion_Entorno.odt](https://github.com/CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood/files/7507355/Interaccion_Entorno.odt)
Subo interacción de elementos y lo paso a verify para darle el visto bueno cuando revisemos.

**Comment by Mimitrz** [comment]
Muy bien desarrollado también, gracias rubenssssssssss

**Comment by ManutiElArtista** [comment]
Ya le he echao un ojo, good jobbbb

**Comment by ManutiElArtista** [comment]
Ya estaría hecho esto no? lo cerramos?

**Comment by vcalzadaga** [comment]
Muy bien chicos. Os lo cierro yo para que os dé avance

**Comment by ManutiElArtista** [comment]
Chiquets resubo los controles :)

![Controles Modificados](https://user-images.githubusercontent.com/90465393/141175794-ebd546a8-301b-47f9-b961-147bcc98cb0c.jpg)

**Comment by Rmp2901** [comment]
![Controles_Mando_Actualizado](https://user-images.githubusercontent.com/90465217/141285534-ef834ad6-a103-472c-8132-2098677b2cd4.jpg)
