### ISSUE TITLE
Diseño de niveles

### ISSUE THREAD

**Issue by Mimitrz** [CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood#11]
- [x] Objetivo del jugador
- [x] Flujo de juegos
- [x] Niveles de juego
- [x] Dificultad
- [x] Tutorial

**Comment by Mimitrz** [comment]
10.1. Objetivo del jugador
El jugador tendrá que superar el nivel atravesando plataformas, trampas y combatiendo con enemigos. También tendrá que recolectar los coleccionables. Estos niveles forman parte de una misión que le será indicada al comienzo de la zona, por lo que el jugador sabrá qué hacer en todo momento.

10.2. Flujo de juego
El jugador, al comenzar a jugar, aparecerá en uno de los diversos puntos de control del juego. Habrá dos situaciones en este punto: El jugador podrá comenzar una misión llegando a una localización indicada en el mapa; o ya estará en una misión en curso y tendrá que completarla, ya sea llegando a un lugar, recolectando un objeto o eliminando enemigos. Tras completar la misión, el jugador será recompensado con equipamiento nuevo, dinero o alguno de los coleccionables del juego. Posteriormente se le indicará la localización de la siguiente misión, y tendrá libertad para acudir a otros lugares antes de comenzar la siguiente aventura, como por ejemplo ir a la tienda o explorar la zona. El objetivo es evitar que el jugador se pierda, siempre indicando a donde debe ir para avanzar en la historia, y dándole un tiempo indefinido entre misiones de libertad para moverse por el mapa.

10.3. Niveles de juego
El juego estará formado por una zona principal que funcionará a modo de hub. Aquí el jugador podrá iniciar la mayoría de misiones, hacer uso de la tienda e incluso pasear o realizar misiones completas en la zona. Alrededor de esta zona se generarán los diferentes niveles. Estos serán de dos tipos diferentes. Unos serán lineales con el único objetivo de llegar hasta el final para completar la misión. El otro tipo estará formado por niveles de navegación libre que tendrán puzzles o pequeñas actividades dentro de la zona para poder completar la misión.

10.4. Dificultad
Existirán 3 niveles diferentes de dificultad. Estos harán que los enemigos tengan más vida y hagan más daño al jugador. El jugador seleccionará el nivel de dificultad al principio del juego, y siempre podrá cambiar la dificultad a lo largo de la historia.

10.5. Tutorial
El tutorial consistirá en un nivel en el que el jugador aprenderá tanto las mecánicas de movimiento para superar las plataformas como las mecánicas de combate para derrotar a los enemigos. Sólo se mostrarán las mecánicas del principio del juego, ya que se irán desbloqueando nuevas habilidades y herramientas a lo largo de la aventura.


Tutorial/primer nivel:
El primer nivel consta de un tutorial exclusivamente de los controles de movimiento para que el jugador comprenda las bases de la jugabilidad principal.
El objetivo es conseguir madera a las afueras de la aldea y volver a casa. 
Comenzando en la casa de Knox, el nivel empieza con 3 zonas que explicaran la movilidad, correr, rodar y todos los movimientos de cámara.
Una vez cruzado el puente, comienza en primer lugar el tutorial de salto, tanto de saltos básicos a saltos cargados o largos. Después se sitúa una pared que Knox deberá trepar. Una vez arriba, el jugador deberá usar la mecánica de agacharse para pasar por un túnel y la de agarrarse a un saliente para cruzar al otro lado. Todas estas zonas no tienen penalización al jugador si esta falla; hay escaleras al principio para volver a intentarlo. Una vez recolectada la madera, el jugador deberá saltar por un saliente que le dejará justo al final del puente para volver a casa.

Segundo nivel: Exploración y combate. 
El nivel dos se sitúa después del ataque de los robots a la aldea, y es el segundo nivel-tutorial. Este se desarrolla únicamente en la aldea, la cual estará con zonas destruidas. El objetivo es llegar a la salida de la aldea eliminando a todos los enemigos. Para empezar, el jugador tendrá que aprender las mecánicas básicas de combate contra un grupo de enemigos. Posteriormente, se le enseñará la funcionalidad de recuperar vida mediante objetos alrededor de los niveles. La segunda zona consta de tutorial sobre la mecánica de ataques a distancia, añadiendo también plataformas de salto. Sigue sin haber penalización al jugador si falla los saltos.
En tercer lugar, habrá una zona de combate con un grupo de enemigos para que asiente las mecánicas de combate. Por último, se realizará un combate contra uno de los jefes del juego, bastante básico.



Tercer nivel: Llegada al origen. 
El tercer nivel da libertad al jugador dando por terminado el tutorial. Este empieza en el puente, y el objetivo es encontrar el origen de los robots. La primera zona es un combate con un grupo de enemigos. Una vez finalizado, el jugador encontrará un pequeño fuerte que le cortará el paso. Tendrá que escalar y una vez arriba, dejarse caer por el agujero en la azotea, que le permitirá meterse dentro y salir usando la mecánica de agacharse. Cuando el jugador salga del fuerte, se tendrá que enfrentar a otro grupo de enemigos. Posteriormente, Knox llegará a la orilla, y tendrá que usar la dinámica de combate en plataformas, unificando mecánicas de combate con mecánicas de salto. Cuando abandone las islas, deberá enfrentarse al segundo jefe del juego, que protege la entrada al portal.


(+ fotos de los mapas de los niveles)

**Comment by Mimitrz** [comment]
Issue acabado!

**Comment by daniloillo** [comment]
Añadir Grafica Dificultad
![GRAFICA DIFICULTAD](https://user-images.githubusercontent.com/90465266/141177570-0d8491c6-2cf6-4754-a5f6-41b12316f529.png)

**Comment by Mimitrz** [comment]
Cerrado!
