### ISSUE TITLE
Música y efectos

### ISSUE THREAD

**Issue by Mimitrz** [CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood#12]

**Comment by Mimitrz** [comment]
Nuestro juego tendrá bandas sonoras de ambiente fantástico con toque celtas, Será una música apropiada con la estética y la historia del videojuego. Aquí dejamos algunos ejemplos de cómo podría ser la música que utilicemos:
https://www.youtube.com/watch?v=rud29JKFPxI&list=PLhfe7jpiJaLGoyd0oV8uUeYZPJWkd22RB 
https://www.youtube.com/watch?v=6KItGlJn__U 
https://youtu.be/HZ3aNv8_-ZE 
https://youtu.be/6tdPhknPRGg 
Al usar las armas, dependiendo de cuál se elija, sonará un efecto de sonido al impactar contra un enemigo. Además si el jugador sufre daño, también sonará como un tipo de quejido. También dependiendo de la zona en la que esté el jugador y dependiendo de la parte de la historia en la que se sitúe, la música variará. En caso de estar en el mundo a través del portal, la música será más tensa por ser un lugar desconocido y no será tan dulce como podría ser en la aldea o en el bosque. El portal también emitirá una especie de sonido espacial o de susurros para atraer al jugador.

**Comment by Mimitrz** [comment]
Issue acabado!

**Comment by vcalzadaga** [comment]
La música encaja perfectamente con el espíritu del juego

Echo de menos algún ejemplo de efectos (sonoro, no sólo la descripción)

**Comment by Mimitrz** [comment]
Algunos efectos sonoros que podríamos usar:
https://youtu.be/WGYMH-HAsKQ (desenfundar arma)
https://youtu.be/7B1FQsE5GSw  (pisadas andando en tierra)
https://youtu.be/iBf_7-mP9lo (para el portal)
https://youtu.be/3Tf6X221c8A (al recolectar cristales)
https://youtu.be/fXoag1v7gxA (para varios impactos o momentos tensos)
https://youtu.be/-pJzv0xr09M (para los robots)
https://youtu.be/kpurvV9zRA8 (para los diálogos, no la voz del animal, el de fondo)
https://youtu.be/A4mN7CsAys8 (los efectos de ambiente)

**Comment by Mimitrz** [comment]
Cerrado!
