### ISSUE TITLE
Alcance

### ISSUE THREAD

**Issue by Mimitrz** [CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood#14]

**Comment by ManutiElArtista** [comment]
He escrito el alcance en el Word, échenle un ojo si gustan.

**Comment by Mimitrz** [comment]
En cuanto a objetos 3D vamos a intentar modelar y texturizar la mayor parte del proyecto, especialmente personajes y escenarios. Quizá necesitaremos utilizar props de alguna librería, ya que el objetivo es tener el tutorial totalmente funcional antes de marzo y tal vez necesitaremos sacrificar trabajo.

**Comment by Mimitrz** [comment]
Issue acabado!
