### ISSUE TITLE
Equipo humano

### ISSUE THREAD

**Issue by Mimitrz** [CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood#16]
- [x] Perfiles profesionales
- [x] Background del equipo

**Comment by ManutiElArtista** [comment]
Esto está completado, si queréis echarle un ojete y me decís.

**Comment by Mimitrz** [comment]
15 EQUIPO HUMANO
15.1. Perfiles profesionales
Rubén: Game Designer, animador 3D, rigger.

Miriam: Programador de interfaz de usuario (UI), ayudante de animación 3D, guionista, sonido (BSO).

Lucía: Artista conceptual, artista conceptual 2D, UI artist, modeladora 3D.

Daniel: Constructor de niveles, ayudante de programación.

Guillermo: Programador de gameplay, programador de IA, programador de físicas.

15.2. Background del equipo
Somos un equipo jóven que nos conocimos en clase mientras realizamos la FP de Animación 3D, entornos interactivos y juegos. Decidimos realizar el GDD juntos ya que a los 5 nos gusta la misma temática y cada uno tenemos unos roles muy claros que conocíamos desde un principio.

**Comment by Mimitrz** [comment]
Issue acabado!
