### ISSUE TITLE
Orden de prioridades

### ISSUE THREAD

**Issue by Mimitrz** [CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood#22]
Ordenar las tareas que debemos hacer por orden de importancia y necesidad

**Comment by alhgo** [comment]
¿Y qué tal pasarlas a la columna de "En proceso"? Porque si no no sé en qué estamos trabajando ahora mismo. En esa columna ya las ordenaremos de arriba a abajo por importancia
