### ISSUE TITLE
Género

### ISSUE THREAD

**Issue by Mimitrz** [CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood#3]

**Comment by Mimitrz** [comment]
El juego supone una unión de varios géneros:
Acción-Aventura: un género basado en la investigación y en los desafíos, además de tomar la fantasía y el misterio como principales elementos de la historia. En Knox and the secret of Ailwood reina dicho género, ya que el principal objetivo del protagonista es investigar el motivo de la invasión a su aldea.
Plataformas 3D: Un género que se basa en el diseño de los niveles a través de plataformas que utilizará el jugador para pasar de nivel y que favorece la exploración del entorno.

**Comment by Lukya98** [comment]
El juego pertenece principalmente a los géneros de acción, ya que se caracteriza porque el jugador debe hacer uso de su velocidad, destreza en el control y tiempo de reacción para avanzar. Al derrotar a los enemigos el jugador tiene que hacer uso de sus reflejos; aventura, caracterizado por la exploración, la investigación, la resolución de puzles, la interacción con personajes y el avance de manera lineal centrado en la trama del juego. El juego esta pensado para tener una trama lineal y en el se podrá interactuar con otros NPC y resolver pequeños y sencillos puzles usando el gancho de nuestro personaje. Y plataformas 3D, porque es un género de videojuegos que se caracterizan por tener que caminar, correr, saltar o escalar sobre una serie de plataformas y acantilados, con enemigos, mientras se recogen objetos para poder completar el juego. Para avanzar en los niveles tendremos que superar ciertos obstáculos del terreno ayudándonos de saltar, correr, escalar y utilizar un gancho. Finalmente, el juego también tiene características de un juego de sigilo en ciertos niveles en los que se propone completarlos de forma sigilosa aun que es totalmente opcional.
