### ISSUE TITLE
Estilo visual

### ISSUE THREAD

**Issue by Mimitrz** [CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood#7]
- [x] Concept art
- [x] Diseño de personajes
- [x] Diseño de escenarios
- [x] Objetos, armas y coleccionables
- [x] Otros

**Comment by Lukya98** [comment]
![COLLAR](https://user-images.githubusercontent.com/90465244/140654242-45b86a1d-b7ef-4f1f-8bb1-e85bfa1acd81.png)

**Comment by Mimitrz** [comment]
![Uploading comerciante.png…](
![gdd_katniss](https://user-images.githubusercontent.com/90465230/140803869-495cc0f1-8b9d-4076-b1de-c7e0c63eec5c.png)
![gdd_Rey](https://user-images.githubusercontent.com/90465230/140803876-6a814eba-bf92-45bd-a6dc-92b228b487f7.png)
![espada](https://user-images.githubusercontent.com/90465230/140803882-ef8ec9d5-7f15-4080-8317-f642175256a0.png)
)
![gdd_stary](https://user-images.githubusercontent.com/90465230/140803889-b03d1678-44a4-414c-88f2-c5f82addea93.png)
![gema](https://user-images.githubusercontent.com/90465230/140803897-73da3c02-2a5b-4c46-957e-ce143821cf73.png)
![ggd_crocko](https://user-images.githubusercontent.com/90465230/140803915-7f88590b-88dc-4840-bff0-a79ce668837a.png)
![ggd_flystrke](https://user-images.githubusercontent.com/90465230/140803920-33272d5f-2b21-43ec-9d26-8e8ed8a0fbe3.png)

![ggd_zumby](https://user-images.githubusercontent.com/90465230/140803942-c176954d-5626-4356-952e-aaad16bdb3fa.png)
![Uploading knox_bg_transparente.png…]()

**Comment by Mimitrz** [comment]
Issue acabado!

**Comment by Lukya98** [comment]
Knox and the secret of Ailwood tendrá un estilo sencillo sin demasiados detalles para no descentrar al jugador de su misión y sea un juego accesible. El estilo visual que mejor encaja es el diseño 3D. Los personajes son animales antropomórficos fantásticos ,los colores vivos y las texturas simples con aspecto cartoon.

Con una paleta de colores inicialmente fría de verdes y azules, porque es un universo natural y con toques de magia y finalmente iremos añadiendo tonos más cálidos y grises por la industrialización creando un contraste entre los posibles escenarios.



Los enemigos con los que nos enfrentemos tendrán un aspecto robótico aunque algunos como el mercader serán amistosos con el jugador aunque tengan aspecto robótico.

Los personajes de la misma raza de knox tendrán pelajes de distintos colores, pueden tener o no cuernos de distintos tipos, altura y constitución distintas.
