### ISSUE TITLE
Interfaz

### ISSUE THREAD

**Issue by Mimitrz** [CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood#8]
- [x] Mapa de navegación
- [x] Menús
- [x] HUD

**Comment by ManutiElArtista** [comment]
El mapa de navegación lo adjunto al comentario este, es el mismo que el del GDD, si quieren echadle un vistazo y podemos cambiar cosas.

[Menu Navegacion.docx](https://github.com/CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood/files/7492526/Menu.Navegacion.docx)

**Comment by ManutiElArtista** [comment]
Los menús hay que ponerlos bonitos porque los que tenemos son muy básicos y feos (los hice yo así que puedo meterme conmigo mismo)

**Comment by ManutiElArtista** [comment]
Subo el HUD, si nos da tiempo podemos intentar hacer uno en bonito con Unity, si no lo dejamos asi.

![Peronaje gamplay bonito](https://user-images.githubusercontent.com/90465393/140651103-eb763998-b05c-47fa-a43e-624e630afef4.jpg)

**Comment by vcalzadaga** [comment]
Tema zanjado (ejemplo)
