### ISSUE TITLE
Dinámicas y mecánicas

### ISSUE THREAD

**Issue by Mimitrz** [CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood#9]

**Comment by Rmp2901** [comment]
Voy a completar está parte del documento chicos.

**Comment by Rmp2901** [comment]
[Dinamicas_Mecanicas.odt](https://github.com/CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood/files/7492617/Dinamicas_Mecanicas.odt)
Revisar cuando podáis la info.

**Comment by ManutiElArtista** [comment]
A mi me parece genial Rubens 👍

**Comment by Rmp2901** [comment]
Lo paso a verify chicos

**Comment by vcalzadaga** [comment]
Este apartado está un poco flojo, demasiado esquemático. Se puede contar mucho más de las mecánicas concretas para este juego: poner ejemplos de su utilización, relacionarlo con las dinámicas de juego, justificar su utilización... Lo muevo a In progress

**Comment by Rmp2901** [comment]
Perfecto Víctor lo revisamos.

**Comment by Rmp2901** [comment]
[Dinamicas_Mecanicas_v2.odt](https://github.com/CIFP-Jose-luis-Garci/KnoxAndTheSecretOfAilwood/files/7506924/Dinamicas_Mecanicas_v2.odt)
Subo la versión actualizada de dinámicas y mecánicas.

**Comment by Mimitrz** [comment]
Están genial, las has desarrollado fenomental <3

**Comment by ManutiElArtista** [comment]
Lo acabo de ver también, ta chulardo Rubens

**Comment by vcalzadaga** [comment]
Fenomenal. Ahora sí que está completo y detallado

Gran trabajo Rubén
